name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with: 
          fetch-depth: 2
      - uses: actions/setup-node@v1
      - run: npm build
      - uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://ftp.cowglow.com/about-me/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          git-ftp-args: --all
          
